const express=require('express');const path=require('path');const fs=require('fs');const crypto=require('crypto');const {spawn}=require('child_process');const {DatabaseSync}=require('node:sqlite');const https=require('https');require('dotenv').config();
const app=express();app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true,limit:'2mb'}));app.use(express.static(path.join(__dirname,'public')));
// Serve the builder UI at the root path as well as static assets.
app.get('/',(req,res)=>{ const candidates=[path.join(__dirname,'public','index.html'),path.join(__dirname,'index.html')]; const file=candidates.find(f=>require('fs').existsSync(f)); if(!file) return res.status(500).send('Frontend file missing: index.html'); res.sendFile(file); });
const DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');const BOT_DIR=path.join(DATA_DIR,'bots');fs.mkdirSync(BOT_DIR,{recursive:true});
const builderDb=new DatabaseSync(path.join(DATA_DIR,'builder.sqlite'));builderDb.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS bots(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,username TEXT NOT NULL,owner_id TEXT NOT NULL,token_enc TEXT NOT NULL,created_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'offline',uptime_started TEXT,last_error TEXT DEFAULT '',db_path TEXT NOT NULL);`);
const children=new Map();const py=process.env.PYTHON_BIN||'python3';
function now(){return new Date().toISOString()}function key(){return crypto.createHash('sha256').update(process.env.BUILDER_SECRET||'change-this-secret').digest()}function enc(s){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv);const d=Buffer.concat([c.update(s,'utf8'),c.final()]);return [iv.toString('base64'),c.getAuthTag().toString('base64'),d.toString('base64')].join('.')}function dec(x){const [iv,t,d]=x.split('.');const c=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64'));c.setAuthTag(Buffer.from(t,'base64'));return Buffer.concat([c.update(Buffer.from(d,'base64')),c.final()]).toString()}
function tg(token,method,body={}){return new Promise((resolve,reject)=>{const data=JSON.stringify(body);const r=https.request(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)},timeout:15000},x=>{let s='';x.on('data',d=>s+=d);x.on('end',()=>{try{resolve(JSON.parse(s))}catch(e){reject(e)}})});r.on('error',reject);r.on('timeout',()=>r.destroy(new Error('Telegram API timeout')));r.write(data);r.end()})}
function validToken(t){return /^\d{5,20}:[A-Za-z0-9_-]{20,}$/.test(String(t||''))}function validOwner(x){return /^\d{5,20}$/.test(String(x||''))}
function dbFor(bot){return new DatabaseSync(bot.db_path)}
function writeEnv(dir,token,owner){const env=`BOT_TOKEN=${token}\nADMIN_USER_ID=${owner}\nDB_PATH=${path.join(dir,'shivam_store.sqlite3')}\nSTORE_TIMEZONE=Asia/Kolkata\nIMAP_ENABLED=0\nIMAP_REQUIRE_TRUSTED_SENDER=1\nIMAP_REQUIRE_RECIPIENT_MATCH=1\n`;fs.writeFileSync(path.join(dir,'.env'),env,{mode:0o600})}
function ensureBotDb(bot){const dir=path.dirname(bot.db_path);fs.mkdirSync(dir,{recursive:true});writeEnv(dir,dec(bot.token_enc),bot.owner_id);}
function startBot(id){const bot=builderDb.prepare('SELECT * FROM bots WHERE id=?').get(id);if(!bot)return false;if(children.has(id))return true;ensureBotDb(bot);const dir=path.dirname(bot.db_path);const child=spawn(py,['bot.py'],{cwd:dir,env:{...process.env,PYTHONUNBUFFERED:'1'},stdio:['ignore','pipe','pipe']});const log=path.join(dir,'bot.log');const append=d=>fs.appendFileSync(log,d);child.stdout.on('data',d=>append(d));child.stderr.on('data',d=>{append(d);builderDb.prepare('UPDATE bots SET last_error=? WHERE id=?').run(String(d).slice(-1500),id)});child.on('exit',(code,signal)=>{children.delete(id);builderDb.prepare("UPDATE bots SET status='offline' WHERE id=?").run(id);if(code!==0){const b=builderDb.prepare('SELECT status FROM bots WHERE id=?').get(id);if(b&&b.status==='online')setTimeout(()=>startBot(id),3000)}});children.set(id,child);builderDb.prepare("UPDATE bots SET status='online',uptime_started=?,last_error='' WHERE id=?").run(now(),id);return true}
function stopBot(id){const c=children.get(id);if(c){c.kill('SIGTERM');children.delete(id)}builderDb.prepare("UPDATE bots SET status='offline' WHERE id=?").run(id);return true}
function restartBot(id){stopBot(id);return startBot(id)}
function rows(bot,sql,args=[]){const d=dbFor(bot);try{return d.prepare(sql).all(...args)}finally{d.close()}}
function run(bot,sql,args=[]){const d=dbFor(bot);try{return d.prepare(sql).run(...args)}finally{d.close()}}
function one(bot,sql,args=[]){const d=dbFor(bot);try{return d.prepare(sql).get(...args)}finally{d.close()}}
function getBot(id){return builderDb.prepare('SELECT * FROM bots WHERE id=?').get(Number(id))}
app.get('/api/health',(q,r)=>r.json({ok:true,status:'online',bots:children.size,time:now()}));
app.get('/api/bots',(q,r)=>r.json({ok:true,bots:builderDb.prepare('SELECT id,name,username,owner_id,created_at,status,uptime_started,last_error FROM bots ORDER BY id DESC').all()}));
app.post('/api/bots/validate',async(q,r)=>{const {token,ownerId}=q.body||{};if(!validToken(token)||!validOwner(ownerId))return r.status(400).json({ok:false,message:'Invalid Bot Token or Telegram Owner ID.'});try{const x=await tg(token,'getMe');if(!x.ok)return r.status(400).json({ok:false,message:x.description||'Telegram rejected the token.'});r.json({ok:true,bot:x.result})}catch(e){r.status(502).json({ok:false,message:e.message})}});
app.post('/api/bots/deploy',async(q,r)=>{const {token,ownerId,name}=q.body||{};if(!validToken(token)||!validOwner(ownerId))return r.status(400).json({ok:false,message:'Invalid Bot Token or Owner ID.'});try{const x=await tg(token,'getMe');if(!x.ok)return r.status(400).json({ok:false,message:x.description||'Token invalid.'});const exists=builderDb.prepare('SELECT id FROM bots WHERE username=?').get(x.result.username);if(exists)return r.status(409).json({ok:false,message:'This bot is already deployed in this builder.'});const id=builderDb.prepare('INSERT INTO bots(name,username,owner_id,token_enc,created_at,status,db_path) VALUES(?,?,?,?,?,'+'\'offline\''+',?)').run(name?.trim()||x.result.first_name||'SHIVAM STORE',x.result.username,String(ownerId),enc(token),now(),path.join(BOT_DIR,String(Date.now())+'-'+crypto.randomBytes(3).toString('hex'),'shivam_store.sqlite3')).lastInsertRowid;const bot=getBot(id);const dir=path.dirname(bot.db_path);fs.mkdirSync(dir,{recursive:true});fs.copyFileSync(path.join(__dirname,'bot_template.py'),path.join(dir,'bot.py'));writeEnv(dir,token,ownerId);startBot(id);r.json({ok:true,bot:{id,username:x.result.username,name:bot.name,owner_id:bot.owner_id,status:'online'}})}catch(e){r.status(500).json({ok:false,message:e.message})}});
app.post('/api/bots/:id/:action',(q,r)=>{const id=Number(q.params.id);if(!getBot(id))return r.status(404).json({ok:false,message:'Bot not found'});if(q.params.action==='start')startBot(id);else if(q.params.action==='stop')stopBot(id);else if(q.params.action==='restart')restartBot(id);else return r.status(400).json({ok:false,message:'Unknown action'});r.json({ok:true})});
app.get('/api/summary/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});const s={members:one(b,'SELECT COUNT(*) c FROM users').c,products:one(b,'SELECT COUNT(*) c FROM products WHERE active=1').c,keys:one(b,"SELECT COUNT(*) c FROM stock_keys WHERE status='available'").c,orders:one(b,'SELECT COUNT(*) c FROM orders').c,delivered:one(b,"SELECT COUNT(*) c FROM orders WHERE delivery_status='delivered'").c,revenue:one(b,"SELECT COALESCE(SUM(amount),0) x FROM orders WHERE status='approved' AND order_type='product'").x,topups:one(b,"SELECT COALESCE(SUM(amount),0) x FROM wallet_transactions WHERE type IN ('deposit','topup') AND amount>0").x};r.json({ok:true,bot:b,stats:s})});
app.get('/api/products/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});const ps=rows(b,`SELECT p.*,COUNT(pl.id) plan_count,(SELECT COUNT(*) FROM stock_keys sk JOIN plans spl ON spl.id=sk.plan_id WHERE spl.product_id=p.id AND sk.status='available') stock FROM products p LEFT JOIN plans pl ON pl.product_id=p.id GROUP BY p.id ORDER BY p.id DESC`);r.json({ok:true,products:ps.map(p=>({...p,status:p.active?'active':'disabled',maintenance:p.maintenance_mode}))})});
function defaultCategory(b){let c=one(b,'SELECT * FROM categories ORDER BY id LIMIT 1');if(!c){run(b,'INSERT INTO categories(name,description,active) VALUES(?,?,1)',['General','Default product category']);c=one(b,'SELECT * FROM categories ORDER BY id LIMIT 1')}return c.id}
app.post('/api/products/:id',(q,r)=>{const b=getBot(q.params.id),x=q.body||{};if(!b)return r.status(404).json({ok:false,message:'Bot not found'});try{const cat=x.category_id||defaultCategory(b);const d=new DatabaseSync(b.db_path);d.exec('BEGIN IMMEDIATE');const p=d.prepare('INSERT INTO products(category_id,name,description,channel_link,maintenance_mode,active,created_at) VALUES(?,?,?,?,?,?,?)').run(cat,String(x.name||'').trim(),String(x.description||''),String(x.channel_link||''),Number(x.maintenance||0),1,now());for(const pl of (x.plans||[])){d.prepare('INSERT INTO plans(product_id,name,description,days,customer_price,reseller_price,active) VALUES(?,?,?,?,?,?,1)').run(p.lastInsertRowid,String(pl.name||pl.duration||'Plan'),String(pl.description||''),Number(pl.days||parseInt(pl.duration)||0),Number(pl.price||0),Number(pl.reseller_price||0))}d.exec('COMMIT');d.close();r.json({ok:true})}catch(e){r.status(400).json({ok:false,message:e.message})}});
app.put('/api/products/:id',(q,r)=>{const x=q.body||{};const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});const p=one(b,'SELECT id FROM products WHERE id=?',[q.params.id]);if(!p)return r.status(404).json({ok:false,message:'Product not found'});run(b,'UPDATE products SET name=COALESCE(?,name),description=COALESCE(?,description),channel_link=COALESCE(?,channel_link),active=COALESCE(?,active),maintenance_mode=COALESCE(?,maintenance_mode) WHERE id=?',[x.name??null,x.description??null,x.channel_link??null,x.status==='disabled'?0:(x.status==='active'?1:null),x.maintenance==null?null:Number(x.maintenance),q.params.id]);r.json({ok:true})});
app.delete('/api/products/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});run(b,'UPDATE products SET active=0 WHERE id=?',[q.params.id]);r.json({ok:true})});
app.get('/api/plans/:id',(q,r)=>{const botId=Number(q.query.bot_id||q.headers['x-bot-id']||0);const b=getBot(botId);if(!b)return r.status(400).json({ok:false,message:'bot_id required'});const ps=rows(b,'SELECT * FROM plans WHERE product_id=? ORDER BY id',[q.params.id]);r.json({ok:true,plans:ps})});
app.post('/api/plans/:id',(q,r)=>{const b=getBot(Number(q.body?.bot_id||q.headers['x-bot-id']||0));if(!b)return r.status(400).json({ok:false,message:'bot_id required'});const x=q.body||{};run(b,'INSERT INTO plans(product_id,name,description,days,customer_price,reseller_price,active) VALUES(?,?,?,?,?,?,1)',[q.params.id,x.name||x.duration||'Plan',x.description||'',Number(x.days||parseInt(x.duration)||0),Number(x.price||0),Number(x.reseller_price||0)]);r.json({ok:true})});
app.get('/api/keys/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});const ks=rows(b,`SELECT sk.*,p.name product,pl.name plan FROM stock_keys sk LEFT JOIN plans pl ON pl.id=sk.plan_id LEFT JOIN products p ON p.id=pl.product_id ORDER BY sk.id DESC`);r.json({ok:true,keys:ks})});
app.post('/api/keys/:id/bulk',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});const list=String(q.body?.keys||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!list.length)return r.status(400).json({ok:false,message:'No keys supplied.'});const planId=Number(q.body?.plan_id||0);const plans=rows(b,'SELECT id FROM plans WHERE id=?',[planId]);if(!plans.length)return r.status(400).json({ok:false,message:'Select a valid plan before adding stock.'});let added=0;const d=new DatabaseSync(b.db_path);d.exec('BEGIN IMMEDIATE');for(const v of list){try{d.prepare('INSERT INTO stock_keys(plan_id,key_value,status,created_at) VALUES(?,? ,\'available\',?)').run(plans[0].id,v,now());added++}catch{}}d.exec('COMMIT');d.close();r.json({ok:true,added})});
app.get('/api/orders/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});const o=rows(b,`SELECT o.*,u.username,u.first_name,p.name product,pl.name plan FROM orders o LEFT JOIN users u ON u.id=o.user_id LEFT JOIN plans pl ON pl.id=o.plan_id LEFT JOIN products p ON p.id=pl.product_id ORDER BY o.id DESC LIMIT 500`);r.json({ok:true,orders:o.map(x=>({...x,user_id:x.user_id,payment:x.status,delivery:x.delivery_status}))})});
app.get('/api/users/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});const u=rows(b,'SELECT id telegram_id,username,first_name,balance,CASE WHEN is_reseller=1 THEN \'reseller\' ELSE \'user\' END role,created_at joined_at FROM users ORDER BY id DESC LIMIT 1000');r.json({ok:true,users:u})});
app.post('/api/wallet/:id',(q,r)=>{const b=getBot(q.params.id),x=q.body||{},amt=Number(x.amount);if(!b||!/^\d+$/.test(String(x.telegram_id||''))||!Number.isFinite(amt)||amt<=0)return r.status(400).json({ok:false,message:'Valid Telegram ID and positive amount required.'});const d=new DatabaseSync(b.db_path);d.exec('BEGIN IMMEDIATE');let u=d.prepare('SELECT * FROM users WHERE id=?').get(Number(x.telegram_id));if(!u)u=d.prepare('SELECT * FROM users WHERE id=?').get(String(x.telegram_id));if(!u){d.exec('ROLLBACK');d.close();return r.status(404).json({ok:false,message:'User not found in this bot.'})}const before=Number(u.balance);const after=before+amt;d.prepare('UPDATE users SET balance=?,updated_at=? WHERE id=?').run(after,now(),u.id);d.prepare('INSERT INTO wallet_transactions(user_id,type,amount,balance_before,balance_after,note,created_at) VALUES(?,?,?,?,?,?,?)').run(u.id,'topup',amt,before,after,String(x.reason||'Admin top-up'),now());d.exec('COMMIT');d.close();r.json({ok:true,balance:after})});
app.get('/api/broadcasts/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});const x=rows(b,'SELECT id,message text,status,sent_count sent,error_count failed,created_at FROM scheduled_broadcasts ORDER BY id DESC LIMIT 100');r.json({ok:true,broadcasts:x})});
app.post('/api/broadcast/:id',(q,r)=>{const b=getBot(q.params.id),text=String(q.body?.text||'').trim();if(!b||!text)return r.status(400).json({ok:false,message:'Message required.'});run(b,'INSERT INTO scheduled_broadcasts(message,run_at,created_at,status) VALUES(?,?,?,\'scheduled\')',[text,now(),now()]);r.json({ok:true})});
app.get('/api/logs/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});const f=path.join(path.dirname(b.db_path),'bot.log');let logs='';try{logs=fs.readFileSync(f,'utf8').slice(-50000)}catch{}r.json({ok:true,logs})});
app.get('/api/config/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});r.json({ok:true,settings:rows(b,'SELECT key,value FROM settings ORDER BY key')})});
app.put('/api/config/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});const d=new DatabaseSync(b.db_path);d.exec('BEGIN IMMEDIATE');for(const [k,v] of Object.entries(q.body||{})){if(!/^[A-Za-z0-9_.-]{1,80}$/.test(k))continue;d.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v??''))}d.exec('COMMIT');d.close();r.json({ok:true})});
app.get('/api/resellers/:id',(q,r)=>{const b=getBot(q.params.id);if(!b)return r.status(404).json({ok:false,message:'Bot not found'});r.json({ok:true,resellers:rows(b,'SELECT id,username,first_name,balance,created_at FROM users WHERE is_reseller=1 ORDER BY id DESC')})});
app.post('/api/resellers/:id',(q,r)=>{const b=getBot(q.params.id),uid=Number(q.body?.user_id);if(!b||!Number.isInteger(uid))return r.status(400).json({ok:false,message:'Valid internal user ID required.'});run(b,'UPDATE users SET is_reseller=1,updated_at=? WHERE id=?',[now(),uid]);r.json({ok:true})});
// Restore running bots on builder restart.
for(const b of builderDb.prepare("SELECT id FROM bots WHERE status='online'").all())try{startBot(b.id)}catch(e){builderDb.prepare('UPDATE bots SET status=\'offline\',last_error=? WHERE id=?').run(e.message,b.id)}
setInterval(()=>{for(const b of builderDb.prepare('SELECT id,status FROM bots').all()){if(b.status==='online'&&!children.has(b.id))startBot(b.id)}},10000);
const PORT=Number(process.env.PORT||3000);app.listen(PORT,()=>console.log(`SHIVAM BOT BUILDER listening on ${PORT}`));
